spring.application.name=ecommerceSpringBoot

# El puerto lo define Render, por eso usamos ${PORT:8080}
server.port=${PORT:8080}

# Activar consola H2 por si quer\u00e9s ver los datos
spring.h2.console.enabled=true

# Config de H2 en memoria (se borra al reiniciar, ideal para demo)
spring.datasource.url=jdbc:h2:mem:ecommerce
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=